---
# file: roles/controlplane/tasks/argocd.yaml

- name: Add helm repository
  become_user: vagrant
  kubernetes.core.helm_repository:
    name: argo
    repo_url: https://argoproj.github.io/argo-helm

- name: Install ArgoCD via helm
  become_user: vagrant
  kubernetes.core.helm:
    name: argocd
    chart_ref: argo/argo-cd
    release_namespace: argocd
    create_namespace: true
    
- name: Install ArgoCD CLI
  become_user: vagrant
  shell: |
    curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
    sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
    rm argocd-linux-amd64

- name: Copy argocd files
  become_user: vagrant
  copy:
    src: "{{ role_path }}/files/argocd/"
    remote_src: no
    dest: /home/vagrant/argocd/

- name: Apply ArgoCD yaml files
  become_user: vagrant
  shell: |
    kubectl apply -f argocd