---
# file: roles/controlplane/tasks/local-path-provisioner.yaml

- name: Install rancher local path provisioner
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.24/deploy/local-path-storage.yaml