---
# file: roles/controlplane/tasks/sealed-secret.yml

# Bootstrap sealed-secrets to use custom certificate. Generate tls.crt and tls.key before running tasks

- name: Copy sealed-secrets certificates
  become_user: root
  copy:
    src: "{{ role_path }}/files/sealed-secrets/"
    remote_src: no
    dest: /opt/sealed-secrets-certificates/
    mode: 0444

- name: Create sealed-secrets tls secret
  become_user: vagrant
  shell: |
    kubectl -n kube-system create secret tls sealed-secrets-keys --cert="/opt/sealed-secrets-certificates/tls.crt" --key="/opt/sealed-secrets-certificates/tls.key"
    kubectl -n kube-system label secret sealed-secrets-keys sealedsecrets.bitnami.com/sealed-secrets-key=active
    kubectl -n kube-system delete pod -l name=sealed-secrets-controller

# ArgoCD will install sealed secrets

# - name: Add helm repository
#   become_user: vagrant
#   kubernetes.core.helm_repository:
#     name: bitnami
#     repo_url: https://charts.bitnami.com/bitnami

# - name: Install Sealed-Secrets via helm
#   become_user: vagrant
#   kubernetes.core.helm:
#     name: sealed-secrets
#     chart_ref: bitnami/sealed-secrets
#     release_namespace: kube-system
#     create_namespace: true