apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: kube-apiserver-dev.yaml
- target:
    kind: Pod
    name: kube-apiserver
    namespace: kube-system
  patch: |-
    - op: add
      path: /spec/containers/0/command/-
      value: --oidc-ca-file=/opt/keycloak-ca/root-ca.pem
- target:
    kind: Pod
    name: kube-apiserver
    namespace: kube-system
  patch: |-
    - op: add
      path: /spec/containers/0/command/-
      value: --oidc-ca-file=/opt/keycloak-ca/root-ca.pem
- target:
    kind: Pod
    name: kube-apiserver
    namespace: kube-system
  patch: |-
    - op: add
      path: /spec/containers/0/command/-
      value: --oidc-issuer-url=https://keycloak.localdev.me/realms/master