---
# file: setup_controlplanes.yaml
- hosts: kubemaster01
  roles:
    - controlplane

- name: Fix Nodes NotReady Status
  hosts: all
  become: true
  tasks:
    - name: systemctl daemon-reload
      ansible.builtin.systemd:
        daemon_reload: yes
    - name: Restart kubelet service
      ansible.builtin.systemd:
        name: kubelet
        state: restarted
    - name: Restart containerd service
      ansible.builtin.systemd:
        name: containerd
        state: restarted
  tags:
    - restart_services